STEPS:
1ST PAGE FOR WEBSITE
LOGIN/SIGNUP
FORGET PASSWORD
HOME
USERS BOOKMARKS/UPLOADED FILES/PREVIOUS-CURRENT WORK    
SEARCH BAR FOR TAGS AND NAMES
RANDOM ACTIVITIES OF SCREEN
IN A PARTICULAR ACTIVITY(SAY FOOD):
SEARCH BAR
-WORK ACCORDING TO RATINGS AND REVIEWS
-ON CLICKING ON A PARTICULAR ACTIVITY 
-PHOTO  
-TOOLS/INGREDIENTS
-PROCESS WITH SIDE TICK OPTIONS TO CLICK TO CHECK HOW MUCH IS DONE
-A PROGRESS BAR
-DISPLAY TAGS
-RATING
-WRITTEN REVIEWS
-SUGGESTED MOVIES/DRINK ETC WHICH CAN BE ADDED BY ANYONE
-REPORT OPTION
-SHARE THE ACTIVITY